### ISSUE TITLE
Price calls need to be mocked

### ISSUE THREAD

**Issue by christroutner** [Permissionless-Software-Foundation/token-liquidity#91]
Got this output from the unit tests:

```
 220 passing (41s)
  2 failing

  1) #token-liquidity
       #getPrice()
         should get the current price from coinbase api:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/trout/work/psf/code/token-liquidity/token-liquidity/test/unit/biz-logic/b07-token-liquidity.lib-unit.js)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)

  2) #token-liquidity
       #getPrice()
         should get price from Coinex if Coinbase fails:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/trout/work/psf/code/token-liquidity/token-liquidity/test/unit/biz-logic/b07-token-liquidity.lib-unit.js)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)

```

These calls need to be mocked for unit tests so that they don't depend on a live network.

**Comment by christroutner** [comment]
Root cause turned out to be the `env-cmd` npm library and its side-effects on tests.
